import type { SubjectInfo } from '../types';

export const subjects: SubjectInfo[] = [
  {
    name: 'Biology',
    icon: 'Dna',
    color: '#10B981',
    bgColor: 'bg-emerald-50',
    textColor: 'text-emerald-700',
    borderColor: 'border-emerald-200',
    chapters: [
      'Ch1: Chemistry of Life',
      'Ch2: Cell Structure & Organelles',
      'Ch3: Cell Membrane & Transport',
      'Ch4: Enzymes & Biological Reactions',
      'Ch5: Cellular Respiration',
      'Ch6: Photosynthesis',
      'Ch7: DNA, RNA & Central Dogma',
      'Ch8: DNA Replication',
      'Ch9: Transcription & Translation',
      'Ch10: Genetics & Inheritance',
      'Ch11: Cell Division',
      'Ch12: Human Anatomy I - Musculoskeletal',
      'Ch13: Human Anatomy II - Circulation & Gas Transport',
      'Ch14: Human Anatomy III - Endocrine System',
      'Ch15: Human Anatomy IV - Digestive System',
      'Ch16: Ecology & Classification',
    ],
  },
  {
    name: 'Chemistry',
    icon: 'FlaskConical',
    color: '#3B82F6',
    bgColor: 'bg-blue-50',
    textColor: 'text-blue-700',
    borderColor: 'border-blue-200',
    chapters: [
      'Ch1: Atomic Structure',
      'Ch2: Periodic Table',
      'Ch3: Chemical Bonding',
      'Ch4: Inorganic Chemistry & Nomenclature',
      'Ch5: Stoichiometry & Reactions',
      'Ch6: Equilibria & Kinetics',
      'Ch7: Redox & Electrochemistry',
      'Ch8: Organic Chemistry',
      'Ch9: Solutions & Gas Laws',
    ],
  },
  {
    name: 'Physics',
    icon: 'Zap',
    color: '#F97316',
    bgColor: 'bg-orange-50',
    textColor: 'text-orange-700',
    borderColor: 'border-orange-200',
    chapters: [
      'Ch1: Mechanics & Kinematics',
      'Ch2: Thermodynamics',
      'Ch3: Electricity & Magnetism',
      'Ch4: Waves & Optics',
      'Ch5: Fluid Mechanics',
      'Ch6: Modern Physics',
    ],
  },
  {
    name: 'Mathematics',
    icon: 'Sigma',
    color: '#8B5CF6',
    bgColor: 'bg-purple-50',
    textColor: 'text-purple-700',
    borderColor: 'border-purple-200',
    chapters: [
      'Ch1: Algebra & Equations',
      'Ch2: Exponents & Logarithms',
      'Ch3: Geometry',
      'Ch4: Trigonometry',
      'Ch5: Probability & Statistics',
      'Ch6: Functions & Graphs',
    ],
  },
  {
    name: 'Logical Reasoning',
    icon: 'Brain',
    color: '#14B8A6',
    bgColor: 'bg-teal-50',
    textColor: 'text-teal-700',
    borderColor: 'border-teal-200',
    chapters: [
      'Ch1: Verbal Logic',
      'Ch2: Numerical Patterns',
      'Ch3: Spatial Reasoning',
      'Ch4: Data Interpretation',
    ],
  },
  {
    name: 'General Knowledge',
    icon: 'Globe',
    color: '#6366F1',
    bgColor: 'bg-indigo-50',
    textColor: 'text-indigo-700',
    borderColor: 'border-indigo-200',
    chapters: [
      'Ch1: History & Culture',
      'Ch2: Geography',
      'Ch3: Politics & International Organizations',
      'Ch4: Science & Technology',
    ],
  },
];

export const mockExamStructure = {
  biology: 23,
  chemistry: 15,
  physics: 6,
  mathematics: 7,
  logicalReasoning: 5,
  generalKnowledge: 4,
  total: 60,
  timeMinutes: 100,
};
